### ISSUE TITLE
Redirection page after post submission

### ISSUE THREAD

**Issue by gouchti** [mikejolley/WP-Job-Manager#461]
I would like you to add the functionality for us to choose a redirection page after people submit a post and send there application, it is very important for many reasons depends on the users, but for me I need it to keep analytic track for people who converts to my advertising goals.

Thanks

**Comment by mikejolley** [comment]
I won't be adding this to core because its not suitable for all users. If you want this, you can filter on the submission steps here https://github.com/mikejolley/WP-Job-Manager/blob/master/includes/forms/class-wp-job-manager-form-submit-job.php#L31 and change the 'preview_handler' to something custom. A developer could assist with this.

Alternatively, the final step fires actions and has its own template file https://github.com/mikejolley/WP-Job-Manager/blob/master/templates/job-submitted.php You could add tracking code there.
