### ISSUE TITLE
issue when adding multiple categories

### ISSUE THREAD

**Issue by kinder2cute** [mikejolley/WP-Job-Manager#468]
Heya,
I am using the plugin through Jobera, I created a page from scratch, I have added the resume functionality and have added few categories to show on the page.

It works fine showing one category each time but when I show multiple it no longer pulls the data.

Page setup
[vc_row full_width=”stretch_row_content_no_spaces” parallax=”” parallax_image=”” type=”0″][vc_column width=”1/1″][featured_products per_page=”12″ columns=”4″ orderby=”” order=””][resumes per_page=”7″ show_filters=”false” show_categories=”true” categories=”architect,mail-sorter”][/vc_column][/vc_row]

The jobera tech team did look into it and mentioned that they have the same issue and I should come and raise a ticket with you.

Many thanks!

**Comment by mikejolley** [comment]
I am aware that Jobera like to give away my extensions for free, so please raise an issue via https://wpjobmanager.com/support/ if you have a licence so I can check prior.

Thanks

**Comment by kinder2cute** [comment]
Hm, I work in IT industry and when we have bugs, if users report it we look into it as at the end of the day it's our systwm and our bugs. So quite responsible for it so when we get the chance to make it better we would. At least that's how works within professionals. 

If you prefer to be known with bugs, suit yourself.

I did mention I am using it through jobera so I cannot raise a ticket there. 

I am not familiar with these themes and what your relationship with jobera is but I may well be a potential client and your ignorance puts off anyone.

PIECE OF CRAP! What a waste. It just proves the custom work is much better! Yes, it can take longer and would cost more but who would be crazy enough to use these plugins which are clunky and hard to adjust to what you need and on top of it when you have bugs there's no support! 

I'll make sure people will know this!

Thanks for your support!

**Comment by mikejolley** [comment]
@kinder2cute If you're not a licensed user, you're not eligible for support from *me*. Jobera are responsible. I did not give them permission to distribute my work.

Also,

1. This is not a issue tracker for resume manager. It's for job manager
2. Using this kind of language does not help your case. Why would anyone want to help you when you say its a piece of crap?
3. I checked out shortcode after you reported it anyway and there was no issue. Multiple categories work as intended.

**Comment by evertsemeijn** [comment]
@kinder2cute If both you and Jobera are having this issue you should check it in a default theme (something like TwentyFifteen). That might help you narrow down the source of the issue: WP Job Manager or Jobera. If you can replicate it in the default theme you should report it to the right place. Since Github is not the right place for support for premium plugins you should send Mike an email. And keep in mind, the resume plugin is a premium plugin, so he might ask you for a license code (I know his avatar looks grumpy, mean and nasty, but he is actually quite nice and quick with solving issues).

You could tell others that you think WP Job Manager is not worth a penny, but scrolling through the Github forum might prove you wrong. Please let us know if you need further assistance!

Cheers and keep smiling (both of you)!

**Comment by kinder2cute** [comment]
Heya,

I had the impression you didn't want to help and left me there.

I did not say your plugin is a piece of crap just in general all the hustle with plugins and themes and just fedup with struggling as I did so far.

Running from one place to another and I am new to themes and plugins and everyone sending me to one place and another

The jobera team told me it's not working with multiple categories for them either and it's an issue I should report here.

The funny thing that individually it does work just not together. It's not pulling through.

If it's working fine on your side, where should I go as it's not working?

Did you ever have this issue on a previous cersion? Perhaps I don't have the latest one?

Thanks! And sorry again for taking it on you.

**Comment by evertsemeijn** [comment]
@kinder2cute Report the issue here https://wpjobmanager.com/support/ You are having an issue with a premium addon. :-)

**Comment by kinder2cute** [comment]
Thanks guys!
I guess this means I don't have support actually as I don't have the licence key, right? :)

**Comment by mikejolley** [comment]
@kinder2cute I tested by assigning 2 categories to a listing, then adding those 2 category slugs to the shortcode. Listing was displayed.

> The jobera team told me it's not working with multiple categories for them either and it's an issue I should report here.

The Jobera team will need to help you and patch if you're using the version they are distributing. As I mentioned, I am aware that they give away my paid extensions for free, but this is without my permission. I only officially support my own licensed users.

Sorry you're caught up in this, but thats what happens when you distribute other peoples work :)

**Comment by evertsemeijn** [comment]
You are right. If you don't have an active license key you can not get support. It is interesting you have the addons without having bought a license (ever?). Be a man and buy the core addons if you want to use them: https://wpjobmanager.com/add-ons/bundle/ And if you received the addons with Jobera you might to report this to Themeforest as well!

**Comment by kinder2cute** [comment]
Hi Mike,

I get where you're coming from and like I mentioned as i am new to all this just learning as I go along.

When I purchased the theme they did advertise as included so as I paid the fee thought I was entitled to have a working product to only be sent here on this ocasion.

What is the latest version just so I can check and compare?

Many thanks!

**Comment by adampickering** [comment]
![img](https://dl.dropboxusercontent.com/spa/nnc1royxnaf5onn/lgvf89ll.jpg)

**Comment by mikejolley** [comment]
1.11.3

**Comment by kinder2cute** [comment]
Hi,

I'll have to look into it and figure out what I actually purchased and what I need in order to get the required functionalities.

Thanks though!

**Comment by kinder2cute** [comment]
Hi adam,

Not sure what to understand from this...

I will however bring all this in duscussion with the theme provider and see what the answer will be...

Thanks!

**Comment by kinder2cute** [comment]
Thanks Mike!
